name: publish release
on:
  release:
    types:
    - released

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm install @vscode/vsce --save-dev
      - run: npm install
      - run: npm run build
      - run: xvfb-run -a npm test
      - name: publish
        run: npm run deploy
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:  
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
